### ISSUE TITLE
Add Webhook Functionality

### ISSUE THREAD

**Issue by rymnc** [trufflesuite/truffle-teams#12]
This is an example of a webhook being sent from GitHub to Discord,

![image](https://user-images.githubusercontent.com/43716372/85846372-56251d00-b7c3-11ea-94d2-b43eb1f096fd.png)

So this usually fires after gh actions runs, 
I believe adding a similar function to truffle teams would be useful for developers to know if their project is building!

Thanks

**Comment by mikeseese** [comment]
Thanks for this suggestion! It might be awhile before we can get to this one however. It's been added to the list though!

**Comment by rymnc** [comment]
Wow okay :)

**Comment by mikeseese** [comment]
Just to update you @aaryamannchallani on this one: we have talked about this one, and it may be awhile before we implement this one due to the complexity to make a robust production-ready version.

However, if you're interested, our Head of Product @DiscRiskandBisque would love to talk to you to learn more about your use case/etc, and perhaps we might be able to prioritize this after that! I'll reach out on Spectrum DMs to get some contact info to make the introduction
